2022-06-04 14:42:18,228 ERROR Internal Server Error: /news/update/46 C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'simpleapp.models.Category.DoesNotExist'>, DoesNotExist('Category matching query does not exist.'), <traceback object at 0x00000158E585DC80>)
Traceback (most recent call last):
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\views\generic\edit.py", line 208, in post
    return super().post(request, *args, **kwargs)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\views\generic\edit.py", line 135, in form_valid
    self.object = form.save()
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\forms\models.py", line 549, in save
    self._save_m2m()
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\forms\models.py", line 530, in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\models\fields\related.py", line 1928, in save_form_data
    getattr(instance, self.attname).set(data)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 1129, in set
    self.remove(*old_ids)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 1068, in remove
    self._remove_items(self.source_field_name, self.target_field_name, *objs)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 1343, in _remove_items
    signals.m2m_changed.send(
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "C:\Users\denpl\PycharmProjects\NewsPortal\project\simpleapp\signals.py", line 26, in notify_managers_appointment
    for i in range(len(Category.objects.get(name=name).subscribers.all())):
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
simpleapp.models.Category.DoesNotExist: Category matching query does not exist.
2022-06-04 14:42:18,267 ERROR "POST /news/update/46 HTTP/1.1" 500 138833 C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-06-04 14:43:09,944 ERROR Internal Server Error: /news/ C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 47: 'endcache', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?"), <traceback object at 0x000001EA05596180>)
Traceback (most recent call last):
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endcache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\templatetags\cache.py", line 84, in do_cache
    nodelist = parser.parse(("endcache",))
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\defaulttags.py", line 954, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 47: 'endcache', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
2022-06-04 14:43:09,963 ERROR "GET /news/?page=2 HTTP/1.1" 500 201388 C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-06-04 14:43:10,329 ERROR Internal Server Error: /news/ C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 47: 'endcache', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?"), <traceback object at 0x000001EA056527C0>)
Traceback (most recent call last):
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endcache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\templatetags\cache.py", line 84, in do_cache
    nodelist = parser.parse(("endcache",))
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\defaulttags.py", line 954, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 47: 'endcache', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
2022-06-04 14:43:10,344 ERROR "GET /news/?page=2 HTTP/1.1" 500 201388 C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
2022-06-06 17:51:06,186 ERROR Internal Server Error: /admin/simpleapp/category/ C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: simpleapp_category.name_af'), <traceback object at 0x000002787C102440>)
Traceback (most recent call last):
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: simpleapp_category.name_af

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\contrib\admin\options.py", line 683, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\contrib\admin\options.py", line 2063, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 302, in __len__
    self._fetch_all()
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: simpleapp_category.name_af
2022-06-06 17:51:06,234 ERROR "GET /admin/simpleapp/category/ HTTP/1.1" 500 214191 C:\Users\denpl\PycharmProjects\NewsPortal\venv\lib\site-packages\django\core\servers\basehttp.py None
